version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crawler_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: crawler_db
      MYSQL_USER: crawler_user
      MYSQL_PASSWORD: crawler_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - crawler_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crawler_backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: crawler_db
      DB_USER: crawler_user
      DB_PASSWORD: crawler_password
      JWT_SECRET: your-secret-key-change-in-production
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - crawler_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crawler_frontend
    environment:
      REACT_APP_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - crawler_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  crawler_network:
    driver: bridge 